Made broker actor obsolete
loekd/ServiceFabric.PubSubActors pull request #54
Opened 2019-02-06 09:05 UTC by loekd

2019-02-10 11:29 UTC, loekd commented
I request a review.

2019-02-13 21:10 UTC, danadesrosiers approved these changes

2019-02-13 21:13 UTC, danadesrosiers commented
A note in the README warning potential users that the BrokerActor/BrokerRelayActor is being phased out would be nice.

2019-02-13 21:18 UTC, danadesrosiers requested changes
There are more references in SubscriberServiceExtensions and SubscriberActorExtensions that should be marked obsolete.

2019-02-19 07:47 UTC, merged

2019-02-19 07:47 UTC, loekd commented
@danadesrosiers thanks, processed the feedback and merged.

2019-02-19 17:53 UTC, danadesrosiers commented on ServiceFabric.PubSubActors/SubscriberServices/SubscriberServiceExtensions.cs
> -        [Obsolete("Use ServiceFabric.PubSubActors.Helpers.SubscriberServiceHelper for testability")]
Did you mean to remove the obsolete attribute from these methods?