Broker Stats
loekd/ServiceFabric.PubSubActors pull request #62
Opened 2019-03-06 16:54 UTC by danadesrosiers

Added some functionality to provide some basic insight into the state of the BrokerService.

* Created two counters in the ReferenceWrapper to record the total number of messages received and delivered for each queue.
* Added endpoint to the BrokerService to allow external services to poll for Broker stats, including a list of all subscribers and the current totals for each queue.
* Added method to BrokerClient to consume the GetBrokerStats() endpoint.  Calls all partitions of the BrokerService and aggregates the results.
* Added method to BrokerClient to unsubscribe a service by queue name.

2019-03-06 20:29 UTC, loekd reviewed
How do you feel about abstracting the implementation behind an interface, e.g. `IStatsCollector`? You could inject an implementation that logs to ETW, or one that logs to memory, etc.

2019-03-07 00:33 UTC, danadesrosiers commented
I think the current implementation would have to change a bit to make that possible, but I'm willing to do it if it adds value.  Can you explain a little more what you are hoping to get out of this?  Right now, it's just incrementing a counter, not logging anything.

2019-03-07 22:16 UTC, danadesrosiers commented
I added some code.  Is that the kind of thing you're think of?  Maybe add a few more callbacks, like `OnSubscribe()` and `OnUnsubscribe()`, so users can implement an `IStatsCollector` to do whatever they need.  It could potentially replace some or all `ServiceEventSourceMessage()` calls.

2019-03-08 06:21 UTC, loekd requested changes

2019-03-08 06:21 UTC, loekd commented on ServiceFabric.PubSubActors/Stats/StatsCollector.cs
> +            subscriber.TotalReceived++;
This is exactly what I mean yes, except for the call to set the `TotalReceived` on the subscriber. I was thinking that this `StatsCollector` could be renamed into `InMemoryStatCollector` (which keeps track of delivered messages in memory) and that we could have alternate implementations, like one that sends a message into ETW and one that sends custom telemetry into AppInsights.

2019-03-08 06:21 UTC, loekd commented on ServiceFabric.PubSubActors/Stats/StatsCollector.cs
> +        }
We could also add `OnMessageDeliveryFailed`

2019-03-08 18:54 UTC, danadesrosiers commented
Closing this pull request so we can delete the SoCreate fork.  New PR is #64.

2019-03-08 18:54 UTC, closed without merging