Service Reference routingkey
loekd/ServiceFabric.PubSubActors pull request #97
Opened 2020-06-19 15:04 UTC by Calidus

Replacement PR For https://github.com/SoCreate/service-fabric-pub-sub/pull/95

Split ```RoutingKey``` into ```RoutingKeyName``` and ```RoutingKeyValue``` in ```ReferenceWrapper```. This should fix issue https://github.com/SoCreate/service-fabric-pub-sub/issues/94. Did not change any interfaces or contracts. Pushed the ```isNullOrWhiteSpace``` check out of ```PublishAsync```and down into ```ShouldDelieverMessage``` to keep all the ```RoutingKeyName``` code together.

```ShouldDelieverMessage``` now converts ```RoutingKeyValue``` into a ```Regex``` and calls ```IsMatch``` instead of using ```string.equals```.  My only concern with this is if someone had reserved regex characters that need to be escaped in their routing key, this change would only be noticeable at run time. If this is an issue we could add a feature flag to the Subscribe Attribute to toggle between ```string.equals``` and ```Regex.IsMatch```

2020-06-19 18:44 UTC, danadesrosiers commented
Yeah, good point about regex reserved characters.  I wouldn't be opposed to adding a parameter to   the `Subscribe` attribute for the routing key RegexOptions.  It could serve as a flag that we want to use regex instead of string compare as well as expose the ability to specify RegexOptions.  But I don't think it's strictly necessary right now.  As long as we clearly document that it is a regex, not a string, it should be fine (I will update the docs when the feature is released).  If anyone was using this feature, we should be more careful, but since it's broken, it's safe to say it's not being used.

2020-06-19 18:47 UTC, danadesrosiers requested changes
Looks good.  We should have a test or two using a regex as the routing key value.

2020-06-20 00:37 UTC, Calidus commented
I thought about adding a test with some regex reserved characters but since RoutingKeyValue always turned into a regex it seems like the only thing I would actually be testing is if the regex class works. "Customer1" is a regex, its just a very boring one. I will do it if you want but I don't know if it really adds any value.

2020-06-22 15:51 UTC, danadesrosiers commented
I think the test is valuable because it verifies that regex functionality is available.  Imagine someone in the future changes the implementation to not use Regex.  Such a test would fail and catch the regression.  In general, tests should not make any assumptions about the implementation of the system under test.  It is definitely not necessary to test all of Regex, just enough to validate that Regex is used.

As for the Key/Value naming, I think it makes sense to update the comment to use Name/Value terminology.

2020-06-22 19:43 UTC, Calidus commented
Do you want RoutingKeyValue renamed to RoutingKeyExpression? or just leave it be?

2020-06-23 16:22 UTC, danadesrosiers approved these changes

2020-06-23 16:25 UTC, danadesrosiers commented
I think `RoutingKeyValue` is fine, but the comment in the `ReferenceWrapper` constructor should use "Name" instead of "Key" to avoid confusion.  I went ahead and made that update and updated the version and changelog so a new version is published when the PR is merged.  Thanks for your contribution!

2020-06-23 16:26 UTC, merged